spring.application.name=catalogo

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

app.jwt.secreto=${JWT_SECRETO}
app.jwt.duracion-ms=3600000

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.jackson.default-property-inclusion=non_null

catalogo.iva=0.19