server.port=8080

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/catalogo}
spring.datasource.username=${DB_USERNAME:catalogo}
spring.datasource.password=${DB_PASSWORD:catalogo}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.com.wposs.catalogo=DEBUG

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

app.cors.origenes=${CORS_ORIGENES:http://localhost:4200}