spring.application.name=catalogo

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/catalogo
spring.datasource.username=catalogo
spring.datasource.password=${DB_PASSWORD:catalogo}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jackson.default-property-inclusion=non_null

logging.level.com.wposs.catalogo=DEBUG

catalogo.iva=0.19